version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: car_rental_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - car-rental-network

  backend:
    build: .
    container_name: car_rental_backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/car_rental?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: your_email@gmail.com
      SPRING_MAIL_PASSWORD: your_app_password
    ports:
      - "8080:8080"
    networks:
      - car-rental-network

volumes:
  mysql_data:

networks:
  ca
